name: Build & Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    tags:
      - "v*.*.*"

jobs:
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64-macos, aarch64-macos]
        optimize: [ReleaseSmall, Debug]
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
      - name: Build
        run: |
          zig build -Dtarget=${{ matrix.target }} -Doptimize=${{ matrix.optimize }}
      - name: Test
        run: |
          zig build test -Dtarget=${{ matrix.target }} -Doptimize=${{ matrix.optimize }}
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [x86_64-windows, aarch64-windows]
        optimize: [ReleaseSmall, Debug]
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
      - name: Build
        run: |
          zig build -Dtarget=${{ matrix.target }} -Doptimize=${{ matrix.optimize }}
      - name: Test
        if: ${{ startsWith(matrix.target, 'x86_64') }}
        run: |
          zig build test -Dtarget=${{ matrix.target }} -Doptimize=${{ matrix.optimize }}
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-linux, aarch64-linux, riscv64-linux]
        optimize: [ReleaseSmall, Debug]
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
      - uses: docker/setup-qemu-action@v3
      - name: Build
        run: |
          zig build -Dtarget=${{ matrix.target }} -Doptimize=${{ matrix.optimize }}
      - name: Test
        run: |
          zig build test -Dtarget=${{ matrix.target }} -Doptimize=${{ matrix.optimize }}
