name: "Label PR"

on:
  pull_request_target:
    types: [edited, opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  labels:
    name: label-pr
    runs-on: ubuntu-24.04-arm
    if: "github.repository_owner == 'PhantomUIx'"
    steps:
      - uses: actions/labeler@v5
